### ISSUE TITLE
Consider renaming @traits macro to @trait

### ISSUE THREAD

**Issue by AzamatB** [schlichtanders/Traits.jl#3]
Because the Julia convention is to name packages with plural form and the rest (macros, structs, etc.) with a singular form.

**Comment by schlichtanders** [comment]
I currently cannot find the reference, where this is stated, but I remember seeing it somewhere.

Nevertheless let me explain, why I've named it `@traits`:
- I wanted to intend that macro supports multiple extra dispatch functions, hence the plural
- I wanted to have a simple package which one single macro, hence I also like the visual simplicity `Traits`, `@traits`

I think the recommendation about naming the package plural form comes mainly from the fact that you cannot name the module the same as a struct from within the module. I.e. things like ``MyStruct.MyStruct`` do not work in Julia. A very intuitive way out is the current convention `MyStructs.MyStruct`. For functions and macros the issues is not that direct, because you have different naming conventions for modules and functions/macros namely capital and non-captital, which can distinguish them here.

My intuition is that it is preferable to leave it `Traits.@traits` for now, as this is the most simple naming possible.

But of course I am open for explanations why it might be better to use `@trait`.

**Comment by schlichtanders** [comment]
I found a good argument: `@trait` macro is currently already widespread to DEFINE new traits. (SimpleTraits, BinaryTraits, CanonicalTraits)

This is not what is happening here. One could think about using `@traitfn` instead, however that is unnecessarily cryptic for this package, as there is only one macro.

Hence will keep `@traits`.
