### ISSUE TITLE
Register the package and its deps

### ISSUE THREAD

**Issue by aminya** [schlichtanders/Traits.jl#8]
I cannot add Traits.jl
```jl
(@v1.4) pkg> add https://github.com/schlichtanders/Traits.jl
    Cloning git-repo `https://github.com/schlichtanders/Traits.jl`
   Updating git-repo `https://github.com/schlichtanders/Traits.jl`
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package StructEquality [6ec83bb0]:
 StructEquality [6ec83bb0] log:
 ├─StructEquality [6ec83bb0] has no known versions!
 └─restricted to versions * by Traits [5060dc80] — no versions left    
   └─Traits [5060dc80] log:
     ├─possible versions are: 0.5.3 or uninstalled
     └─Traits [5060dc80] is fixed to version 0.5.3


```

**Comment by schlichtanders** [comment]
Please see the installation instructions https://github.com/schlichtanders/Traits.jl#installation--import

it is currently distributed via a custom registry until all dependencies are stable enough to put them into General registry

**Comment by aminya** [comment]
Thanks. I know I can add them manually. 

But without having Traits being registered I cannot add this as a dependency. This means I cannot use Traits in my package.

**Comment by schlichtanders** [comment]
dear @aminya. Traits is registered in a Julia Registry, just not in General, but in SchlichtandersJuliaRegistry, including all its dependencies.

Please take a look at the link I provided for you, it takes you to the installation instructions of Traits.jl where you are asked to add a custom registry before adding Traits.jl.

Because you seem to have some problems opening the link, I copy the important content here for you:
```
using Pkg
pkg"registry add https://github.com/JuliaRegistries/General"  # central julia repository
pkg"registry add https://github.com/schlichtanders/SchlichtandersJuliaRegistry.jl"  # custom repository
pkg"add Traits"
```
